wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.16.0
    framework: xgboost
    huggingface_version: 4.46.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737126686.526981
    t:
      1:
      - 1
      - 3
      - 5
      - 6
      - 11
      - 12
      - 30
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 3
      - 5
      - 6
      - 11
      - 12
      - 30
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 7
      - 13
      - 19
      - 23
      4: 3.11.11
      5: 0.16.0
      6: 4.46.1
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
vocab_size:
  desc: null
  value: 151936
max_position_embeddings:
  desc: null
  value: 32768
hidden_size:
  desc: null
  value: 896
intermediate_size:
  desc: null
  value: 4864
num_hidden_layers:
  desc: null
  value: 24
num_attention_heads:
  desc: null
  value: 14
use_sliding_window:
  desc: null
  value: false
sliding_window:
  desc: null
  value: null
max_window_layers:
  desc: null
  value: 24
num_key_value_heads:
  desc: null
  value: 2
hidden_act:
  desc: null
  value: silu
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-06
use_cache:
  desc: null
  value: false
rope_theta:
  desc: null
  value: 1000000.0
rope_scaling:
  desc: null
  value: null
attention_dropout:
  desc: null
  value: 0.0
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: bfloat16
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - Qwen2ForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 151643
pad_token_id:
  desc: null
  value: null
eos_token_id:
  desc: null
  value: 151645
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: Qwen/Qwen2-0.5B-Instruct
_attn_implementation_autoset:
  desc: null
  value: true
transformers_version:
  desc: null
  value: 4.46.1
model_type:
  desc: null
  value: qwen2
output_dir:
  desc: null
  value: saves/qwen2-0.5b/full/sft
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 2
per_device_eval_batch_size:
  desc: null
  value: 2
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 8
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
torch_empty_cache_steps:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: cosine
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.05
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: saves/qwen2-0.5b/full/sft/runs/Jan17_15-10-02_5af8fb2322d5
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 20
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 1000
dataloader_num_workers:
  desc: null
  value: 0
dataloader_prefetch_factor:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: saves/qwen2-0.5b/full/sft
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
deepspeed:
  desc: null
  value: /content/Moonshot_Interview/LLaMA-Factory/examples/deepspeed/ds_z0_config.json
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
include_for_metrics:
  desc: null
  value: []
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
evaluation_strategy:
  desc: null
  value: null
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 180000000
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
split_batches:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
use_liger_kernel:
  desc: null
  value: false
eval_use_gather_object:
  desc: null
  value: false
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: false
generation_max_length:
  desc: null
  value: 1024
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value: null
ray_run_name:
  desc: null
  value: null
ray_num_workers:
  desc: null
  value: 1
resources_per_worker:
  desc: null
  value:
    GPU: 1
placement_strategy:
  desc: null
  value: PACK
model/num_parameters:
  desc: null
  value: 494032768
model_args:
  desc: null
  value:
    vllm_maxlen: 4096
    vllm_gpu_util: 0.9
    vllm_enforce_eager: false
    vllm_max_lora_rank: 32
    vllm_config: null
    export_dir: null
    export_size: 1
    export_device: cpu
    export_quantization_bit: null
    export_quantization_dataset: null
    export_quantization_nsamples: 128
    export_quantization_maxlen: 1024
    export_legacy_format: false
    export_hub_model_id: null
    image_resolution: 262144
    video_resolution: 16384
    video_fps: 2.0
    video_maxlen: 64
    quantization_method: bitsandbytes
    quantization_bit: null
    quantization_type: nf4
    double_quantization: true
    quantization_device_map: null
    model_name_or_path: Qwen/Qwen2-0.5B-Instruct
    adapter_name_or_path: null
    adapter_folder: null
    cache_dir: null
    use_fast_tokenizer: true
    resize_vocab: false
    split_special_tokens: false
    new_special_tokens: null
    model_revision: main
    low_cpu_mem_usage: true
    rope_scaling: null
    flash_attn: auto
    shift_attn: false
    mixture_of_depths: null
    use_unsloth: false
    use_unsloth_gc: false
    enable_liger_kernel: false
    moe_aux_loss_coef: null
    disable_gradient_checkpointing: false
    use_reentrant_gc: true
    upcast_layernorm: false
    upcast_lmhead_output: false
    train_from_scratch: false
    infer_backend: huggingface
    offload_folder: offload
    use_cache: true
    infer_dtype: auto
    hf_hub_token: <HF_HUB_TOKEN>
    ms_hub_token: <MS_HUB_TOKEN>
    om_hub_token: <OM_HUB_TOKEN>
    print_param_status: false
    trust_remote_code: false
    compute_dtype: torch.bfloat16
    device_map:
      ? ''
      : cuda:0
    model_max_length: 1024
    block_diag_attn: false
data_args:
  desc: null
  value:
    template: qwen
    dataset:
    - qwen_train_data
    eval_dataset: null
    dataset_dir: data
    image_dir: data
    cutoff_len: 1024
    train_on_prompt: false
    mask_history: false
    streaming: false
    buffer_size: 16384
    mix_strategy: concat
    interleave_probs: null
    overwrite_cache: true
    preprocessing_batch_size: 1000
    preprocessing_num_workers: 16
    max_samples: null
    eval_num_beams: null
    ignore_pad_token_for_loss: true
    val_size: 0.1
    packing: false
    neat_packing: false
    tool_format: null
    tokenized_path: null
finetuning_args:
  desc: null
  value:
    use_swanlab: false
    swanlab_project: llamafactory
    swanlab_workspace: null
    swanlab_run_name: null
    swanlab_mode: cloud
    swanlab_api_key: <SWANLAB_API_KEY>
    use_badam: false
    badam_mode: layer
    badam_start_block: null
    badam_switch_mode: ascending
    badam_switch_interval: 50
    badam_update_ratio: 0.05
    badam_mask_mode: adjacent
    badam_verbose: 0
    use_apollo: false
    apollo_target:
    - all
    apollo_rank: 16
    apollo_update_interval: 200
    apollo_scale: 32.0
    apollo_proj: random
    apollo_proj_type: std
    apollo_scale_type: channel
    apollo_layerwise: false
    apollo_scale_front: false
    use_galore: false
    galore_target:
    - all
    galore_rank: 16
    galore_update_interval: 200
    galore_scale: 2.0
    galore_proj_type: std
    galore_layerwise: false
    pref_beta: 0.1
    pref_ftx: 0.0
    pref_loss: sigmoid
    dpo_label_smoothing: 0.0
    kto_chosen_weight: 1.0
    kto_rejected_weight: 1.0
    simpo_gamma: 0.5
    ppo_buffer_size: 1
    ppo_epochs: 4
    ppo_score_norm: false
    ppo_target: 6.0
    ppo_whiten_rewards: false
    ref_model: null
    ref_model_adapters: null
    ref_model_quantization_bit: null
    reward_model: null
    reward_model_adapters: null
    reward_model_quantization_bit: null
    reward_model_type: lora
    additional_target: null
    lora_alpha: 16
    lora_dropout: 0.0
    lora_rank: 8
    lora_target:
    - all
    loraplus_lr_ratio: null
    loraplus_lr_embedding: 1.0e-06
    use_rslora: false
    use_dora: false
    pissa_init: false
    pissa_iter: 16
    pissa_convert: false
    create_new_adapter: false
    freeze_trainable_layers: 2
    freeze_trainable_modules:
    - all
    freeze_extra_modules: null
    pure_bf16: false
    stage: sft
    finetuning_type: full
    use_llama_pro: false
    use_adam_mini: false
    freeze_vision_tower: true
    freeze_multi_modal_projector: true
    train_mm_proj_only: false
    compute_accuracy: false
    disable_shuffling: false
    plot_loss: true
    include_effective_tokens_per_second: false
generating_args:
  desc: null
  value:
    do_sample: true
    temperature: 0.95
    top_p: 0.7
    top_k: 50
    num_beams: 1
    max_new_tokens: 1024
    repetition_penalty: 1.0
    length_penalty: 1.0
    default_system: null
    skip_special_tokens: true
